config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'home', to: 'pages#index', as: 'home'
  get '/', to: 'pages#index'
  get 'about', to: 'pages#about', as: 'about'
  get 'contact', to: 'pages#contact', as: 'contact'
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  get 'register', to: 'users#new', as: 'register'
  get 'signup', to: 'users#new', as: 'signup'
  post 'add_friend/:user_id', to: 'users#add_friend', as: 'add_friend'
  resources :cities
  resources :continents
  resources :countries do
    resources :comments do
      resources :likes
      resources :dislikes
    end
  end

  resources :discussions do
    resources :posts
  end
  resources :users do
    member do
      get :friends
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :country, optional: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :country

  has_many :likes, dependent: :destroy
  has_many :dislikes, dependent: :destroy

  has_many :replies, class_name: 'Comment', foreign_key: :reply_id
  belongs_to :parent, class_name: 'Comment', foreign_key: :reply_id, optional: true

  def get_commenter
    User.find(user_id)
  end
end

app/models/continent.rb
class Continent < ApplicationRecord
  has_many :countries
end

app/models/country.rb
class Country < ApplicationRecord
  belongs_to :continent, optional: true
  has_many :cities, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :user
  has_many :posts, dependent: :destroy
  accepts_nested_attributes_for :posts
end

app/models/dislike.rb
class Dislike < ApplicationRecord
  belongs_to :user
  belongs_to :comment

  def already_disliked?
    Disike.where(user_id: @current_user.id, comment_id:
        params[:comment_id]).exists?
  end
end

app/models/friendrequest.rb
class Friendrequest < ApplicationRecord
  belongs_to :requester, class_name: 'User'
  belongs_to :receiver, class_name: 'User'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :comment

  def already_liked?
    Like.where(user_id: @current_user.id, comment_id:
        params[:comment_id]).exists?
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :discussion
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :likes
  has_many :dislikes

  has_many :friends, class_name: 'User', foreign_key: :friend_id
  belongs_to :owner, class_name: 'User', foreign_key: :friend_id, optional: true

  has_many :received, class_name: 'Friendrequest', foreign_key: 'receiver_id'
  has_many :requests, class_name: 'Friendrequest', foreign_key: 'requester_id'
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  include SessionsHelper

  before_action :check_access, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_discussion, only: [:show, :edit, :update, :destroy]

  # GET /discussions
  # GET /discussions.json
  def index
    @discussions = Discussion.all
  end

  # GET /discussions/1
  # GET /discussions/1.json
  def show
  end

  # GET /discussions/new
  def new
    @discussion = Discussion.new
    @discussion.posts.build
  end

  # GET /discussions/1/edit
  def edit
  end

  # POST /discussions
  # POST /discussions.json
  def create
    @discussion = Discussion.new(discussion_params)

    respond_to do |format|
      if @discussion.save
        format.html { redirect_to @discussion, notice: 'Discussion was successfully created.' }
        format.json { render :show, status: :created, location: @discussion }
      else
        format.html { render :new }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discussions/1
  # PATCH/PUT /discussions/1.json
  def update
    respond_to do |format|
      if @discussion.update(discussion_params)
        format.html { redirect_to @discussion, notice: 'Discussion was successfully updated.' }
        format.json { render :show, status: :ok, location: @discussion }
      else
        format.html { render :edit }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discussions/1
  # DELETE /discussions/1.json
  def destroy
    @discussion.destroy
    respond_to do |format|
      format.html { redirect_to discussions_url, notice: 'Discussion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_discussion
    @discussion = Discussion.find(params[:id])
  end

    # Never trust parameters from the scary internet, only allow the white list through.
  def discussion_params
    params.require(:discussion).permit(:user_id, :title, posts_attributes: [:user_id, :content, :_destroy])
  end

  def check_access
      redirect_back(fallback_location: discussions_url) if current_user.nil?
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/continents_helper.rb
module ContinentsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
  def parse_countries
    source = 'https://restcountries.eu/rest/v2/all'
    resp = Net::HTTP.get_response(URI.parse(source))
    data = resp.body
    result = JSON.parse(data)
  end
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/helpers/dislikes_helper.rb
module DislikesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out()
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/discussions/_form.html.erb
<%= form_with(model: discussion, local: true) do |form| %>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <br>

  <%= form.fields_for :posts do |posts_form| %>
    <%= posts_form.hidden_field :user_id, value: current_user.id %>
    <%= posts_form.label "Content:" %><br>
    <%= posts_form.text_area :content, class: 'form-control' %>
  <% end %>

  <br>

  <div class="actions">
    <%= form.submit class: 'form-control btn btn-success' %>
  </div>

  <br>
<% end %>

app/views/discussions/edit.html.erb
<h1>Editing Discussion</h1>

<%= render 'form', discussion: @discussion %>

<%= link_to 'Show', @discussion %> |
<%= link_to 'Back', discussions_path %>

app/views/discussions/index.html.erb
<% provide(:title, "Discussion Board") %>

<h1 class="text-center">Discussion Board</h1>

<main role="main" class="container">
  <div class="jumbotron col-md-12" style="margin: 0 auto">
    <% @discussions.each do |discussion| %>
      <div class="card">
        <div class="card-header">
          <h3><%= link_to discussion.title, discussion, class: 'standard-link' %></h3>
        </div>
        <div class="card-body">
          <%= discussion.posts.last.content %>
          <br><br>
          <p><%= link_to discussion.posts.last.user.username, user_path(discussion.posts.last.user.username), class: 'standard-link' %> -
            <%= time_ago_in_words(discussion.posts.last.created_at) %> ago.</p>
        </div>
        <div class="card-footer">
          <% if logged_in? && current_user.id === discussion.user.id %>
            <%= link_to '<i class="far fa-edit"></i> Edit'.html_safe, edit_discussion_path(discussion), class: 'btn btn-primary' %>
            <%= link_to '<i class="fas fa-times"></i> Delete'.html_safe, discussion, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
          <% end %>
        </div>
      </div>
      <hr>
    <% end %>

    <br>

    <%= link_to '<i class="fas fa-plus"></i> New Discussion'.html_safe, new_discussion_path, class: 'btn btn-primary' %>
  </div>
</main>

<br>

app/views/discussions/new.html.erb
<h1 class="text-center">New Discussion</h1>

<main role="main" class="container">
  <div class="jumbotron col-md-8" style="margin: 0 auto">
    <%= render 'form', discussion: @discussion %>
    <%= link_to 'Back', discussions_path, class: 'btn btn-danger' %>
  </div>
</main>

app/views/discussions/show.html.erb
<% provide(:title, @discussion.title) %>

<h1 class="text-center">
  <%= @discussion.title %> by
  <%= link_to @discussion.user.username, user_path(@discussion.user), class: 'standard-link' %>
</h1>

<main role="main" class="container">
  <div class="jumbotron col-md-12" style="margin: 0 auto">
    <%= render @discussion.posts %>
    <br>
  <% if logged_in? %>
    <%= render 'posts/form' %>
  <% else %>
    <p>You cannot join the conversation until you have <%= link_to 'logged in', login_path, class: 'standard-link' %>.</p>
  <% end %>
  <%= link_to 'Back', discussions_path, class: 'btn btn-danger' %>
  </div>
</main>