config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'home', to: 'pages#index', as: 'home'
  get '/', to: 'pages#index'
  get 'about', to: 'pages#about', as: 'about'
  get 'contact', to: 'pages#contact', as: 'contact'
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  get 'register', to: 'users#new', as: 'register'
  get 'signup', to: 'users#new', as: 'signup'
  post 'add_friend/:user_id', to: 'users#add_friend', as: 'add_friend'
  resources :cities
  resources :continents
  resources :countries do
    resources :comments do
      resources :likes
      resources :dislikes
    end
  end

  resources :discussions do
    resources :posts
  end
  resources :users do
    member do
      get :friends
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :country, optional: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :country

  has_many :likes, dependent: :destroy
  has_many :dislikes, dependent: :destroy

  has_many :replies, class_name: 'Comment', foreign_key: :reply_id
  belongs_to :parent, class_name: 'Comment', foreign_key: :reply_id, optional: true

  def get_commenter
    User.find(user_id)
  end
end

app/models/continent.rb
class Continent < ApplicationRecord
  has_many :countries
end

app/models/country.rb
class Country < ApplicationRecord
  belongs_to :continent, optional: true
  has_many :cities, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :user
  has_many :posts, dependent: :destroy
  accepts_nested_attributes_for :posts
end

app/models/dislike.rb
class Dislike < ApplicationRecord
  belongs_to :user
  belongs_to :comment

  def already_disliked?
    Disike.where(user_id: @current_user.id, comment_id:
        params[:comment_id]).exists?
  end
end

app/models/friendrequest.rb
class Friendrequest < ApplicationRecord
  belongs_to :requester, class_name: 'User'
  belongs_to :receiver, class_name: 'User'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :comment

  def already_liked?
    Like.where(user_id: @current_user.id, comment_id:
        params[:comment_id]).exists?
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :discussion
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :likes
  has_many :dislikes

  has_many :friends, class_name: 'User', foreign_key: :friend_id
  belongs_to :owner, class_name: 'User', foreign_key: :friend_id, optional: true

  has_many :received, class_name: 'Friendrequest', foreign_key: 'receiver_id'
  has_many :requests, class_name: 'Friendrequest', foreign_key: 'requester_id'
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper

  before_action :authenticate, only: %i[index show edit]
  before_action :set_user, only: %i[show edit update destroy friends]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        log_in @user
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_friend
    @request = Friendrequest.create(requester_id: current_user.id, receiver_id: params[:user_id])
    current_user.requests << @request
    User.find(params[:user_id]).received << @request
    redirect_back(fallback_location: root_url)
  end

  def friends
    @friends = @user.friends
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

    # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
  
  def authenticate
    unless logged_in?
      redirect_back(fallback_location: root_url)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/continents_helper.rb
module ContinentsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
  def parse_countries
    source = 'https://restcountries.eu/rest/v2/all'
    resp = Net::HTTP.get_response(URI.parse(source))
    data = resp.body
    result = JSON.parse(data)
  end
end

app/helpers/dislikes_helper.rb
module DislikesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out()
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, class: 'form-control' %>
  </div>

  <br>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email, class: 'form-control' %>
  </div>

  <br>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, class: 'form-control' %>
  </div>

  <br>

  <div class="actions">
    <%= form.submit class: 'form-control btn btn-success' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/friends.html.erb
<% provide(:title, "#{@user.username}'s Friends") %>

<main role="main" class="container">
  <div class="jumbotron col-md-8" style="margin: 0 auto">
    <h1><%= @user.username %>'s Friends</h1>
    <br>
    <ul>
      <% @friends.each do |friend| %>
        <li><%= link_to friend.username, friend, class: 'standard-link' %></li>
      <% end %>
    </ul>
  </div>
</main>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% provide(:title, "Register") %>

<br>

<h1 class="text-center">Register</h1>

<br>

<main role="main" class="container">
  <div class="jumbotron col-md-8" style="margin: 0 auto">
    <%= render 'form', user: @user %>
    <br>
    Already have an account? Log in <%= link_to 'here', login_path, class: 'standard-link' %>.
    <br>
    <%= link_to 'Back', _back_url, class: 'btn btn-danger' %>
  </div>
</main>

app/views/users/show.html.erb
<% provide(:title, @user.username) %>

<main role="main" class="container">
  <div class="jumbotron col-md-8" style="margin: 0 auto">
    <h1 class="text-center"><%= @user.username %></h1>
      <% if current_user != nil && current_user.id == @user.id %>
        <p class="text-center"><strong>Email: </strong>
        <%= @user.email %></p>
      <% end %>
      <p class="text-center"><strong>Friends: </strong>
      <ul>
        <% @user.friends.each do |friend| %>
          <li><%= link_to friend.username, friend, class: 'standard-link' %></li>
        <% end %>
      </ul>
      <div class="text-center">
          <%= @user.requests[0].requester.username %>
          <% if current_user != nil && current_user.id == @user.id %>
            <% if @user.requests.any? %>
              <ul>
                <% @user.requests do |request| %>
                  <li><%= request.requester.username %></li>
                <% end %>
              </ul>
            <% end %>
            <% if @user.received.any? %>
              <ul>
                <% @user.received do |received| %>
                  <li><%= received.receiver.username %></li>
                <% end %>
              </ul>
            <% end %>
            <%= link_to 'Edit', edit_user_path(@user), class: 'btn btn-primary' %>
          <% elsif current_user != nil && current_user.id != @user.id && @user.friend_id != current_user.id %>
            <%= link_to 'Add Friend', add_friend_path(@user.id), class: 'btn btn-primary', method: :post %>
          <% end %>
          <%= link_to 'Back', users_path, class: 'btn btn-danger' %>
      </div>
  </div>
</main>