config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'home', to: 'pages#index', as: 'home'
  get '/', to: 'pages#index'
  get 'about', to: 'pages#about', as: 'about'
  get 'contact', to: 'pages#contact', as: 'contact'
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  get 'register', to: 'users#new', as: 'register'
  get 'signup', to: 'users#new', as: 'signup'
  post 'add_friend/:user_id', to: 'users#add_friend', as: 'add_friend'
  resources :cities
  resources :continents
  resources :countries do
    resources :comments do
      resources :likes
      resources :dislikes
    end
  end

  resources :discussions do
    resources :posts
  end
  resources :users do
    member do
      get :friends
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :country, optional: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :country

  has_many :likes, dependent: :destroy
  has_many :dislikes, dependent: :destroy

  has_many :replies, class_name: 'Comment', foreign_key: :reply_id
  belongs_to :parent, class_name: 'Comment', foreign_key: :reply_id, optional: true

  def get_commenter
    User.find(user_id)
  end
end

app/models/continent.rb
class Continent < ApplicationRecord
  has_many :countries
end

app/models/country.rb
class Country < ApplicationRecord
  belongs_to :continent, optional: true
  has_many :cities, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :user
  has_many :posts, dependent: :destroy
  accepts_nested_attributes_for :posts
end

app/models/dislike.rb
class Dislike < ApplicationRecord
  belongs_to :user
  belongs_to :comment

  def already_disliked?
    Disike.where(user_id: @current_user.id, comment_id:
        params[:comment_id]).exists?
  end
end

app/models/friendrequest.rb
class Friendrequest < ApplicationRecord
  belongs_to :requester, class_name: 'User'
  belongs_to :receiver, class_name: 'User'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :comment

  def already_liked?
    Like.where(user_id: @current_user.id, comment_id:
        params[:comment_id]).exists?
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :discussion
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :likes
  has_many :dislikes

  has_many :friends, class_name: 'User', foreign_key: :friend_id
  belongs_to :owner, class_name: 'User', foreign_key: :friend_id, optional: true

  has_many :received, class_name: 'Friendrequest', foreign_key: 'receiver_id'
  has_many :requests, class_name: 'Friendrequest', foreign_key: 'requester_id'
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  require 'net/http'
  before_action :set_country, only: [:show, :edit, :update, :destroy]

  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.all
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
    @continent = Continent.find(@country.continent_id) unless @country.continent_id.nil?
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Country was successfully created.' }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1
  # PATCH/PUT /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_url, notice: 'Country was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def country_params
      params.require(:country).permit(:continent_id, :name, :description, { city_ids: [] })
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/continents_helper.rb
module ContinentsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
  def parse_countries
    source = 'https://restcountries.eu/rest/v2/all'
    resp = Net::HTTP.get_response(URI.parse(source))
    data = resp.body
    result = JSON.parse(data)
  end
end

app/helpers/dislikes_helper.rb
module DislikesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out()
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/countries/_form.html.erb
<%= form_with(model: country, local: true) do |form| %>
  <% if country.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
      <% country.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control'  %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control'  %>
  </div>

  <div class="field">
      <%= form.label "Cities" %>
    <%= hidden_field_tag "country[city_ids][]", nil %>
    <% City.all.each do |city| %>
      <label class="checkbox-inline">
        <%= check_box_tag "country[city_ids][]", city.id, form.object.cities.include?(city) %> <%= city.name %>
      </label>
    <% end %>
    <% unless City.any? %>
      <span>It looks like there are no cities on the system click <%= link_to :here, new_city_path %> to create some!</span>
    <% end %>
  </div>

  <div class="field">
      <%= form.label "Continent" %>
    <% if Continent.any? %>
      <%= form.select :continent_id, Continent.all.collect { |c| [ c.name, c.id ] }, class: 'form-control' %>
    <% else %>
      <span>It looks like there are no continents on the system click <%= link_to :here, new_continent_path %> to create some!</span>
    <% end %>
  </div>

  <div class="actions">
    <%=  form.submit class: 'form-control btn btn-success' %>
  </div>
  <% end %>

app/views/countries/edit.html.erb
<% provide(:title, "Editing " + @country.name) %>

<h1 class="text-center">Editing <%= link_to @country.name, @country, class: 'standard-link' %></h1>

<main role="main" class="container">
  <div class="jumbotron col-md-8" style="margin: 0 auto">
    <%= render 'form', country: @country %>
    <%= link_to 'Back', countries_path, class: 'btn btn-danger' %>
  </div>
</main>

app/views/countries/index.html.erb
<% provide(:title, "Countries") %>

<h1 class="text-center">Countries</h1>

<main role="main" class="container">
  <div class="jumbotron col-md-8" style="margin: 0 auto">
    <% @countries.each do |country| %>
      <div class="card">
        <div class="card-header">
          <h3><%= link_to country.name, country_path(country), class: 'standard-link' %></h3>
        </div>
        <div class="card-body">
          <%= country.description %>
        </div>
        <div class="card-footer">
          <span>
            <%= link_to '<i class="far fa-edit"></i> Edit'.html_safe, edit_country_path(country), class: 'btn btn-primary' %>
            <%= link_to '<i class="fas fa-times"></i> Delete'.html_safe, country, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
          </span>
        </div>
      </div>
      <br>
    <% end %>

    <br>

    <%= link_to '<i class="fas fa-plus"></i> New Country'.html_safe, new_country_path, class: 'btn btn-primary' %>
  </div>
</main>

app/views/countries/new.html.erb
<% provide(:title, "New Country") %>

<h1 class="text-center">New Country</h1>

<main role="main" class="container">
  <div class="jumbotron col-md-8" style="margin: 0 auto">
    <%= render 'form', country: @country %>
    <br>
    <%= link_to 'Back', countries_path, class: 'standard-link' %>
  </div>
</main>

app/views/countries/show.html.erb
<% provide(:title, @country.name) %>

<br>

<div class="container">
  <h1><%= @country.name %> <small><%= link_to 'Edit', edit_country_path(@country), class: 'standard-link' %></small></h1>

  <br>

  <div class="description">
    <%= @country.description %>
  </div>

  <br>

  <div>
    <strong>Cities:</strong>
    <% unless @country.cities.any? %>
      <span>There are currently no cities here...</span>
    <% end %>
    <ul>
      <% @country.cities.each do |city| %>
        <li><%= link_to city.name, city_path(city), class: 'standard-link' %></li>
      <% end %>
    </ul>
  </div>

  <br>

  <div>
    <strong>Continent:</strong>
    <% if defined? @continent %>
      <%= link_to @continent.name, continent_path(@continent), class: 'standard-link' %>
    <% else %>
      <span>There is currently no continent here...</span>
    <% end %>
  </div>

  <br>

  <div>
    <h3><a id="comment-link" href="#comment-link" class="standard-link"><%= @country.comments.count %>
      Comment<%= 's' if @country.comments.count > 1  %> <span id="toggle-arrow"><i class="fas fa-angle-double-down"></i></span></a></h3>
    <div id="comments-div" style="display: none;">
      <%= render @country.comments.where(:reply_id => nil) %>
      <% if logged_in? %>
        <%= render 'comments/form' %>
      <% else %>
        <span>You must <%= link_to :login, login_path, class: 'standard-link' %> to post a comment on <%= @country.name %>.</span>
      <% end %>
    </div>
  </div>


  <br>

  <%= link_to 'Back', countries_path, class: 'btn btn-danger' %>
</div>

<br>