config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'home', to: 'pages#index', as: 'home'
  get '/', to: 'pages#index'
  get 'about', to: 'pages#about', as: 'about'
  get 'contact', to: 'pages#contact', as: 'contact'
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  get 'register', to: 'users#new', as: 'register'
  get 'signup', to: 'users#new', as: 'signup'
  post 'add_friend/:user_id', to: 'users#add_friend', as: 'add_friend'
  resources :cities
  resources :continents
  resources :countries do
    resources :comments do
      resources :likes
      resources :dislikes
    end
  end

  resources :discussions do
    resources :posts
  end
  resources :users do
    member do
      get :friends
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :country, optional: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :country

  has_many :likes, dependent: :destroy
  has_many :dislikes, dependent: :destroy

  has_many :replies, class_name: 'Comment', foreign_key: :reply_id
  belongs_to :parent, class_name: 'Comment', foreign_key: :reply_id, optional: true

  def get_commenter
    User.find(user_id)
  end
end

app/models/continent.rb
class Continent < ApplicationRecord
  has_many :countries
end

app/models/country.rb
class Country < ApplicationRecord
  belongs_to :continent, optional: true
  has_many :cities, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :user
  has_many :posts, dependent: :destroy
  accepts_nested_attributes_for :posts
end

app/models/dislike.rb
class Dislike < ApplicationRecord
  belongs_to :user
  belongs_to :comment

  def already_disliked?
    Disike.where(user_id: @current_user.id, comment_id:
        params[:comment_id]).exists?
  end
end

app/models/friendrequest.rb
class Friendrequest < ApplicationRecord
  belongs_to :requester, class_name: 'User'
  belongs_to :receiver, class_name: 'User'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :comment

  def already_liked?
    Like.where(user_id: @current_user.id, comment_id:
        params[:comment_id]).exists?
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :discussion
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :likes
  has_many :dislikes

  has_many :friends, class_name: 'User', foreign_key: :friend_id
  belongs_to :owner, class_name: 'User', foreign_key: :friend_id, optional: true

  has_many :received, class_name: 'Friendrequest', foreign_key: 'receiver_id'
  has_many :requests, class_name: 'Friendrequest', foreign_key: 'requester_id'
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/continents_helper.rb
module ContinentsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
  def parse_countries
    source = 'https://restcountries.eu/rest/v2/all'
    resp = Net::HTTP.get_response(URI.parse(source))
    data = resp.body
    result = JSON.parse(data)
  end
end

app/helpers/dislikes_helper.rb
module DislikesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out()
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="font-small">
  <div class="footer-copyright text-center py-3">© 2019 Copyright:
    <a href="https://github.com/brycekennedy117" class="standard-link" target="_blank"> Bryce Kennedy</a>
  </div>
</footer>

app/views/layouts/_head.html.erb
<title><%= yield(:title) %> | Country Exchange</title>
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <ul class="navbar-nav">
      <li class="nav-item"><%= link_to 'Country Exchange', root_url, class: 'navbar-brand' %></li>
      <li class="nav-item"><%= link_to 'Countries', countries_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to 'Cities', cities_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to 'Continents', continents_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to 'Discussions', discussions_path, class: 'nav-link' %></li>
    </ul>
    <ul class="navbar-nav flex-row ml-md-auto d-none d-md-flex">
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <span class="nav-link dropdown-toggle" id="navbardrop" data-toggle ="dropdown">
              <%= @current_user.username %>
            </span>
            <div class="dropdown-menu">
              <%= link_to 'Profile', user_path(@current_user), class: 'dropdown-item' %>
              <%= link_to 'Logout', logout_path, method: :delete, class: 'dropdown-item' %>
            </div>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link p-2' %></li>
          <li class="nav-item"><%= link_to 'Register', register_path, class: 'nav-link p-2' %></li>
        <% end %>
    </ul>
  </nav>
</header>

<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/head' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div id="wrapper">
      <%= yield %>
    </div>
    <div id="push"></div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/index.html.erb
<% provide(:title, "Welcome!") %>